# Generated by Django 5.1.6 on 2025-02-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftschedule',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shiftschedule',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shiftschedule',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
