# Generated by Django 5.1.6 on 2025-02-26 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_shiftschedule_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinaryaction',
            name='duration_measure',
            field=models.CharField(default='asasas', max_length=64),
            preserve_default=False,
        ),
    ]
