stages:
  - deploy

deploy_stagging:
  stage: deploy
  only:
    - Stagging
  script:
    - echo "Deploy to Stagging..."
    - ssh $STAG_USER$STAG_HOST << 'EOF'
        cd /stagging_pusatdata
        git pull
        pip install pipenv
        pipenv shell
        pipenv install -r requirements.txt
        pipenv run python server/manage.py makemigrations
        pipenv run python server/manage.py migrate
        pipenv run python server/manage.py migrate sales --database=sales
        pipenv run python server/manage.py migrate master --database=master
        pipenv run python server/manage.py migrate
        exit
        sudo systemctl restart gunicorn
      EOF

# deploy_production:
#   stage: deploy
#   only:
#     - main
#   script:
#     - echo "Deploying to Production..."
#     - ssh $PROD_USER@PROD_HOST << 'EOF'
#         cd /stagging_pusatdata
#         git pull
#         pip install pipenv
#         pipenv shell
#         pipenv install -r requirements.txt
#         pipenv run python3 server/manage.py makemigrations
#         pipenv run python3 server/manage.py migrate
#         pipenv run python3 server/manage.py migrate sales --database=sales
#         pipenv run python3 server/manage.py migrate master --database=master
#         pipenv run python3 server/manage.py migrate
#         exit
#         sudo systemctl restart gunicorn
#       EOF
        
