"""
WARNING TO THE NEXT DEVELOPER:

I have no idea why this worked.
After approximately 90 hours of intense frustration, rubber duck debugging,
almost 1 gallons of coffee, one existential crisis, and briefly considering a career change,
FINALLY I GOT IT WORKING.

DO NOT TOUCH unless you willing to go to the same emotional journey.

You've been warned. Good Luck :D

- Signed, Past Me (who barely made it out ALIVE)
"""

"""
Django settings for master_data project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import json
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%ui#t=6)11fpu802x8&^974%tr)k8ojg_v!%au-*qyr79@+!_m'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", cast=bool, default=False)

ALLOWED_HOSTS = config("ALLOWED_HOSTS", cast=Csv())
CSRF_TRUSTED_ORIGINS = [config("CSRF_SERVICE", default="http://localhost:8000")]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_browser_reload',
    'human_resource',
    'master',
    'sales',
    'supplier'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'master.middleware.AutoLogout',
    'django_browser_reload.middleware.BrowserReloadMiddleware',
]

ROOT_URLCONF = 'master_data.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'master_data', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'master_data.wsgi.application'


# Databases
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": config("DB_DEFAULT_ENGINE", default="django.db.backends.sqlite3"),
        "NAME": config("DB_DEFAULT_NAME", default=f"{BASE_DIR} / databases/auth.sqlite3"),
        "USER": config("DB_DEFAULT_USER", default=""),
        "PASSWORD": config("DB_DEFAULT_PASSWORD", default=""),
        "HOST": config("DB_DEFAULT_HOST", default=""),
        "PORT": config("DB_DEFAULT_PORT", default=""),
        "CONN_MAX_AGE": 0,
    },
    "master": {
        "ENGINE": config("DB_MASTER_ENGINE", default="django.db.backends.sqlite3"),
        "NAME": config("DB_MASTER_NAME", default=f"{BASE_DIR} / databases/master.sqlite3"),
        "USER": config("DB_MASTER_USER", default=""),
        "PASSWORD": config("DB_MASTER_PASSWORD", default=""),
        "HOST": config("DB_MASTER_HOST", default=""),
        "PORT": config("DB_MASTER_PORT", default=""),
        "CONN_MAX_AGE": 0,
    },
    "sales": {
        "ENGINE": config("DB_SALES_ENGINE", default="django.db.backends.sqlite3"),
        "NAME": config("DB_SALES_NAME", default=f"{BASE_DIR} / databases/sales.sqlite3"),
        "USER": config("DB_SALES_USER", default=""),
        "PASSWORD": config("DB_SALES_PASSWORD", default=""),
        "HOST": config("DB_SALES_HOST", default=""),
        "PORT": config("DB_SALES_PORT", default=""),
        "CONN_MAX_AGE": 0,
    },
    "supplier": {
        "ENGINE": config("DB_SUPPLIER_ENGINE", default="django.db.backends.sqlite3"),
        "NAME": config("DB_SUPPLIER_NAME", default=f"{BASE_DIR} / databases/supplier.sqlite3"),
        "USER": config("DB_SUPPLIER_USER", default=""),
        "PASSWORD": config("DB_SUPPLIER_PASSWORD", default=""),
        "HOST": config("DB_SUPPLIER_HOST", default=""),
        "PORT": config("DB_SUPPLIER_PORT", default=""),
        "CONN_MAX_AGE": 0,
    },
    "human_resource": {
        "ENGINE": config("DB_HR_ENGINE", default="django.db.backends.sqlite3"),
        "NAME": config("DB_HR_NAME", default=f"{BASE_DIR} / databases/hr.sqlite3"),
        "USER": config("DB_HR_USER", default=""),
        "PASSWORD": config("DB_HR_PASSWORD", default=""),
        "HOST": config("DB_HR_HOST", default=""),
        "PORT": config("DB_HR_PORT", default=""),
        "CONN_MAX_AGE": 0,
    },
}

DATABASE_ROUTERS = [
    'human_resource.routers.HumanResourceRouter',
    'master.routers.MasterRouter',
    'sales.routers.SalesRouter',
    'supplier.routers.SupplierRouter',
]

AUTO_LOGOUT_TIME = int(60 * 60)

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Jakarta'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = config("STATIC_URL", default="/static/")
STATIC_ROOT = config("STATIC_ROOT", default="staticfiles")
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

MEDIA_URL = config("MEDIA_URL", default="media/")
MEDIA_ROOT = config("MEDIA_ROOT", default="media")

LOGIN_URL = '/login/'

LOGIN_REDIRECT_URL = 'transaction/doctor-list/'

SESSION_EXPIRE_AT_BROWSER_CLOSE = True

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.gmail.com'

EMAIL_PORT = 587

EMAIL_USE_TLS = True

EMAIL_HOST_USER = 'satriodasmdi@gmail.com'

EMAIL_HOST_PASSWORD = 'kmdu qboa nezv cpcj'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SECURE_PROXY_SSL_HEADER = tuple(
    config("SECURE_PROXY_SSL_HEADERS").split(",")
)

CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', cast=bool)
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', cast=bool)
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', cast=bool)
SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', cast=bool)
SECURE_HSTS_INCLUDE_SUBDOMAINS = config('SECURE_HSTS_INCLUDE_SUBDOMAINS', cast=bool)
SECURE_HSTS_PRELOAD = config('SECURE_HSTS_PRELOAD', cast=bool)

API_JAMET=config("API_JAMET")