# Generated by Django 5.1.6 on 2025-02-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('entity', models.IntegerField()),
                ('branch', models.IntegerField()),
                ('warehouse', models.IntegerField()),
                ('sp_number', models.TextField(blank=True, null=True)),
                ('sj_number', models.TextField(blank=True, null=True)),
                ('fj_number', models.TextField(blank=True, null=True)),
                ('department', models.IntegerField()),
                ('is_otc', models.BooleanField(blank=True, null=True)),
                ('sales', models.IntegerField()),
                ('customer', models.IntegerField()),
                ('product_detail', models.TextField()),
                ('detail_sales', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'report_sales',
                'managed': True,
            },
        ),
    ]
