# Generated by Django 5.1.6 on 2025-02-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.TextField()),
                ('type_complaint', models.IntegerField()),
                ('product', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'complaints',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales', models.IntegerField(blank=True, null=True)),
                ('target', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'target_sales',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales', models.IntegerField()),
                ('type_visits', models.IntegerField(blank=True, null=True)),
                ('customer', models.IntegerField(blank=True, null=True)),
                ('products', models.TextField(blank=True, null=True)),
                ('c_in_date', models.DateTimeField(blank=True, null=True)),
                ('c_in_image', models.ImageField(blank=True, null=True, upload_to='media/user_upload_file/sales/')),
                ('c_in_address', models.TextField(blank=True, null=True)),
                ('c_out_date', models.DateTimeField(blank=True, null=True)),
                ('c_out_image', models.ImageField(blank=True, null=True, upload_to='media/user_upload_file/sales/')),
                ('c_out_address', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_sub', models.BooleanField()),
                ('parent', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'visits',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='salesreport',
            name='hna',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
