# Generated by Django 5.1.6 on 2025-02-20 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('code', models.CharField(max_length=24)),
                ('full_name', models.CharField(max_length=64)),
                ('entity', models.IntegerField(blank=True, null=True)),
                ('branch', models.IntegerField(blank=True, null=True)),
                ('public_information', models.TextField(blank=True, null=True)),
                ('work_information', models.TextField(blank=True, null=True)),
                ('private_information', models.TextField(blank=True, null=True)),
                ('work_loaction', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'employee',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=64)),
                ('entity', models.IntegerField(blank=True, null=True)),
                ('branch', models.IntegerField(blank=True, null=True)),
                ('public_information', models.TextField(blank=True, null=True)),
                ('work_information', models.TextField(blank=True, null=True)),
                ('private_information', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'recruitment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TimeOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('date', models.DateField()),
                ('time_off_type', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'time_off',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Disciplinary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_resource.employee')),
            ],
            options={
                'db_table': 'disciplinary',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.CharField(max_length=64)),
                ('deductions', models.TextField(blank=True, null=True)),
                ('net_salary', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_resource.employee')),
            ],
            options={
                'db_table': 'payroll',
                'managed': True,
            },
        ),
    ]
